= Demystifying Ansible Automation Platform on OpenShift Container Platform Lab
:sectnums:
:toc: left
:toclevels: 2
:experimental:

[#welcome]
== 👋 Welcome to the Lab!

Welcome to the **Demystifying Ansible Automation Platform (AAP) on OpenShift Container Platform (OCP)** lab at Red Hat One!

In this lab, we are going to dive deep into troubleshooting Ansible Automation Platform deployments on OpenShift. You will work through practical exercises focused on the AAP Operator to help demonstrate where to look to find out what is going on with the deployment and how to fix some of the most common issues the Ansible SBR encounters.

---

[#environment]
== 🖥️ Your Environment

* Each student has their own **Single Node OpenShift cluster** with cluster administrator access.
* All of the work for the lab will be done on the **Bastion host** provided.

[TIP]
.Bastion Host Pre-Configuration
The Bastion host has been pre-configured with:
* The `oc` client (OpenShift CLI).
* The required Ansible modules and collections.
* All other resources needed to complete the lab.

---

[#scenarios]
== 🧩 Lab Scenarios Overview

You have **8 scenarios** to work through, covering each major component of Ansible Automation Platform:

* **Gateway**
* **Controller**
* **Automation Hub**
* **Event-Driven Ansible (EDA)**
* **Ansible Lightspeed Intelligent Assistant (ALIA)**

### The Lab Workflow

The core workflow for each scenario is:

1.  Run the playbook to **deploy** the scenario.
2.  Run the playbook to **break** the scenario.
3.  **Troubleshoot** and figure out what is going on.
4.  Once you have found the issues (or if you get stuck), run the playbook to **fix** the scenario and see the steps taken to resolve the issues.

---

[#get-started]
== 🚀 Getting Started

To get started with the lab, please complete the following steps:

.   **SSH into the Bastion Host**
    [source,bash]
    ----
    ssh `{bastion_ssh_user_name}`@`{bastion_public_hostname}` -p `{bastion_ssh_port}`
    Use password `{bastion_ssh_password}` when prompted.
    ----

.   **Access OpenShift UI**
    [source,bash]
    ----
    OpenShift Console available at: `{openshift_console_url}`
    OpenShift Admin username: `{openshift_cluster_admin_username}`
    OpenShift Admin password: `{openshift_cluster_admin_password}`
    ----    

.   **Access OpenShift CLI**
    [source,bash]
    ----
    oc whoami
    ----       

.   **Clone the Repository**
    Change into your working directory and clone the lab repository.
    [source,bash]
    ----
    git clone https://github.com/your-repo/this-lab.git
    cd this-lab
    ----

.   **Deploy Initial Resources**
    Deploy the core AAP resources and start with Scenario 1.
    [source,bash]
    ----
    ansible-playbook site.yml
    # Then select scenario 1 to get started
    ----

++++
<p style="text-align: center; font-size: 1.5em; margin-top: 2em;"><strong>Good luck and have fun!</strong></p>
++++