# Scenario #3: Gateway Issues

[#scenario-03,cols="3"]
.Scenario #3: Gateway Issues
|===
| **Mode** | **Components** | **Namespace**

| Hard
| Automation Controller, Gateway
| `aap-rh1`
|===

### 📝 Objectives

* Log in to the **AAP Gateway UI**.
* Observe connectivity failures
* Diagnose two separate issues
* Resolve both issues to restore full functionality.

---

### 🛠️ Prerequisites: Setup and Break

#### 1. Initial Deployment

[.instruction]
====
Execute the following command, then select **Scenario 3** when prompted.
====

[source,bash]
----
ansible-playbook site.yml
----

[NOTE]
====
The deployment can take up to 15 minutes, now would be a good time to take a break, ask any questions, hydrate.
====

#### 2. Introduce Failure (Break)

[.instruction]
====
Execute the following command, then select **Scenario 3** when prompted.
====

[source,bash]
----
ansible-playbook site.yml -t break

----

### ✅ Troubleshooting and Resolution

#### Step 1: Check Pod Logs

[.instruction]
====
**CLI Method:** Review Gateway pod logs.
====

[source,bash]
----
oc logs -n aap-rh1 <Gateway-pod-name>
oc get svc -n aap-rh1
----

[.instruction]
====
**UI Method:**
1. Navigate to **Workloads** -> **Pods** and view the logs for the `aap-gateway` pod for errors.
2. Navigate to **Networking** -> **Services** in the OpenShift console. Check for any missing service.
====

#### Step 2: Attempt logging in to AAP.

[.instruction]
====
Attempt to log into the AAP Gateway UI. Review gateway pod logs
====

#### Step 3: Implement the Fixes

[.instruction]
====
Once you have diagnosed the issues, follow the specific resolution steps located in the solution document: **xref:scenario-3-solution.adoc[3.1. Solution: Gateway Issues]**
====

#### Step 4: Verify Resolution

[.instruction]
====
Verify all pods are running and ready, then successfully log into the AAP UI.
====

[source,bash]
----
oc get pods -n aap-rh1
----

---

### 💡 Hint

* There are two issues here, you aren't expected to know how to fix the issues, only to discover what the issue is. Run the fix playbook to fix the first issue when you know what it is.
* Once the first issue is resolved, log back into AAP, review logs, and determine the issue. You aren't expected to know how to fix this issue, only to discover what the issue is. Rerun the fix playbook to fix the second issue when you know what it is.
[.instruction]
====
Execute the following command, then select **Scenario 3** when prompted.
====

[source,bash]
----
ansible-playbook site.yml -t fix

----